trigger:
  - main
  - feature

pool: default

variables: 
  - name: work_dir
    value: '$(System.DefaultWorkingDirectory)\Env\Dev'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: terraforminitandplan
        displayName: terraform init and plan job
        pool: default
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(work_dir)
            backendServiceArm: 'deepak_service_new'
            backendAzureRmStorageAccountName: 'deep57stg'
            backendAzureRmContainerName: 'deepcnt'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(work_dir)
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(work_dir)
            environmentServiceNameAzureRM: 'deepak_service_new'


  - stage: scanning
    displayName: scanning
    jobs:
      - job: terraformtfsec
        displayName: tfsec
        pool: default
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: $(work_dir)

  - stage: deploy
    displayName: deploy
    jobs:
      - job: manualvalidation
        displayName: manaul validation
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'deepakkumar10038@gmail.com'
            approvers: 'deepakkumar10038@gmail.com'


      - job: terraformapply
        displayName: terraform job apply
        dependsOn: manualvalidation
        pool: Default
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(work_dir)
            backendServiceArm: 'deepak_service_new'
            backendAzureRmStorageAccountName: 'deep57stg'
            backendAzureRmContainerName: 'deepcnt'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: $(work_dir)
            environmentServiceNameAzureRM: 'deepak_service_new'

        